version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    image: ${DOCKER_IMAGE_NAME}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}

  db:
    image: postgres:13-buster
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
